// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWFPGq6b6GEc6KCe_fkfxTi6-NpYC_B3I',
    appId: '1:434884841806:web:20e7352a796ce4082f0e1f',
    messagingSenderId: '434884841806',
    projectId: 'sample-989c9',
    authDomain: 'sample-989c9.firebaseapp.com',
    databaseURL: 'https://sample-989c9-default-rtdb.firebaseio.com',
    storageBucket: 'sample-989c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgW3X8gfUorjlMcVWzlpkOkWb8CeUX3no',
    appId: '1:434884841806:android:a49f3973e854aaee2f0e1f',
    messagingSenderId: '434884841806',
    projectId: 'sample-989c9',
    databaseURL: 'https://sample-989c9-default-rtdb.firebaseio.com',
    storageBucket: 'sample-989c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJPaBT_P_Bg0D8-p6emXV2RGLJAcJ9O8',
    appId: '1:434884841806:ios:89a056fa112512532f0e1f',
    messagingSenderId: '434884841806',
    projectId: 'sample-989c9',
    databaseURL: 'https://sample-989c9-default-rtdb.firebaseio.com',
    storageBucket: 'sample-989c9.appspot.com',
    iosClientId: '434884841806-19gsibunnq60kmp40h80bhlma767u1oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAJPaBT_P_Bg0D8-p6emXV2RGLJAcJ9O8',
    appId: '1:434884841806:ios:81bfe2e6b07c637c2f0e1f',
    messagingSenderId: '434884841806',
    projectId: 'sample-989c9',
    databaseURL: 'https://sample-989c9-default-rtdb.firebaseio.com',
    storageBucket: 'sample-989c9.appspot.com',
    iosClientId: '434884841806-jpgokh3293f31k28if049e8a9sacaeh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
